version: '3.8'

services:
  backend:
    build: ./server
    container_name: adgen_backend
    ports:
      - "5000:5000"
    volumes:
      - ./server/videos:/app/videos
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - GROQ_API_KEY=${GROQ_API_KEY}
    env_file:
      - .env
  
  frontend:
    build:
      context: ./client
    container_name: adgen_frontend
    ports:
      - "3000:80"  
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
